repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt --check
        entry: nix develop --command cargo fmt --check
        language: system
        pass_filenames: false
      - id: cargo-clippy
        name: cargo clippy
        entry: nix develop --command cargo clippy --all-targets --all-features -- -D warnings
        language: system
        pass_filenames: false
